### ISSUE TITLE
Need help setting up Annotation-Studio

### ISSUE THREAD

**Issue by aschle** [hyperstudio/Annotation-Studio#35]
I am trying to run Annotation-Studio on a debian server. Now it is running, but I cant register any user.

I could not find any help on how to set up `conf/application.yml`.

```
development:
    GOOGLE_VERIFICATION_CODE:
    DEFAULT_USER_GROUP: public
    GOOGLE_ANALYTICS_CODE:
    ENVIRONMENT_TAG:
    DEFAULT_USERS_CAN_CHOOSE_GROUPS: true
    DEFAULT_USERS_CAN_CONTROL_PERMISSIONS: true
    DEFAULT_USERS_CAN_CREATE_TEXTS: true
    DEFAULT_USERS_CAN_SEE_OTHERS_WORK: true
    GMAIL_USER: # to send user emails while in development
    GMAIL_PASS: # to send user emails while in development
    UNICORN_BACKLOG: 16
    # make the following the path to your local (or hosted) instance of the MIT-Annotation-Data-Store
    API_URL: http://localhost:5000/
    API_SECRET:
    API_CONSUMER: localhost
    CONFIRMATION_GRACE_PERIOD: 2
```

![bildschirmfoto vom 2014-03-06 16 06 01](https://f.cloud.github.com/assets/883797/2346312/ec91d874-a540-11e3-9e5d-e1799a4d75a0.png)

Could somebody help me please? I guess the configuration is not quite right?
Cheers Alexa
